service: squabble-${sls:stage}-price

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  apiGateway:
    restApiName: ${env:API_GW_RESOURCE_NAME}-${sls:stage}
  environment:
    APP_STAGE: ${sls:stage}
    APP_SECRET: ${env:APP_SECRET}
    AWS_PARTITION: ${env:AWS_PARTITION}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    AWS_REGION: ${env:AWS_REGION}
    FMP_API_KEY: ${env:FMP_API_KEY}
    AWS_ACCESS_KEY: ${env:AWS_ACCESS_KEY}
  stackName: squabble-${sls:stage}-price
  role:
    Fn::GetAtt:
      - ServiceIAMRole
      - Arn
  deploymentBucket:
    name: squabble-${sls:stage}-serverless-deployment
    maxPreviousDeploymentArtifacts: 2
    blockPublicAccess: true
    skipPolicySetup: true
    versioning: false

resources:
  Resources:
    ServiceIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: squabble-${sls:stage}-price
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: squabble-${sls:stage}-price
            PolicyDocument:
              Version: '2012-10-17'
              Statement: ${self:provider.iamRoleStatements}
    PriceHistoryTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: organizationId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: organizationId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: squabble-${sls:stage}-price-data
        Tags:
          - Key: platform
            Value: squabble
          - Key: platform-environment
            Value: ${sls:stage}
          - Key: platform-component
            Value: platform
          - Key: platform-region
            Value: ${env:AWS_REGION}
          - Key: platform-service
            Value: price
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  getPriceHistory:
    handler: src/price.getPriceHistory
    name: squabble-${sls:stage}-price-getPriceHistory
    events:
      - http:
          path: /get-price-history
          method: get
          cors: true
          private: true